### ISSUE TITLE
Cannot upload project avatar: 'avatar is invalid'

### ISSUE THREAD

**Issue by danepowell** [m4tthumphrey/php-gitlab-api#739]
[Our project calls `uploadAvatar()`](https://github.com/acquia/cli/blob/fae9193756f42a2b873b573327a6747067e96b66/src/Command/CodeStudio/CodeStudioCommandTrait.php#L253) after creating a GitLab project. I'm pretty sure this has worked in the past, but recently stopped working, throwing an `avatar is invalid` exception: https://github.com/acquia/cli/issues/1377

I did some debugging and it looks like a problem with this library. A curl request with the same avatar to the same API endpoint works fine:

`curl --location --request PUT 'https://code.acquia.com/api/v4/projects/1092' --header 'Authorization: Bearer [snip]' --form 'avatar=@drupal_icon.png'`

I suspect GitLab changed something in the expected file or PUT format that's breaking this call.

**Comment by ajuchacko** [comment]
Yes, curl command works.
<img width="1426" alt="Screenshot 2023-03-15 at 7 51 29 PM" src="https://user-images.githubusercontent.com/13982547/225345834-97c90248-9519-443b-90d4-075175eb6c76.png">


I am not sure if this was working since day one. **[ea09dc7](https://github.com/GitLabPHP/Client/commit/ea09dc71966839c3290459b90c58fc0b1d9c47fb)**
<img width="1394" alt="Screenshot 2023-03-15 at 8 11 41 PM" src="https://user-images.githubusercontent.com/13982547/225345293-474cf5b7-8f19-4bad-9047-ccdc5137d3f3.png">

**Comment by ajuchacko** [comment]
Yo, [Dane powell](@danepowell) I saw a mr on gitlab made last year which has something to do with trailing slash. 
So probably this would have been working in the past I guess.

**Comment by danepowell** [comment]
Looks like this was fixed in #750, thanks!
